services:
  postgres:
    image: postgres:15
    container_name: roaming-postgres
    environment:
      POSTGRES_DB: roaming-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Asia/Seoul
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d roaming_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: