server:
  port: 8091

spring:
  application:
    name: roaming-data-synchronizer
  
  docker:
    compose:
      enabled: false
  
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always
  
  datasource:
    url: jdbc:postgresql://localhost:5433/roaming-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  logging:
    level:
      org.springframework.batch: INFO
      com.roaming: DEBUG