spring:
  application:
    name: roaming-data-synchronizer
  
  batch:
    job:
      enabled: false
  
  datasource:
    url: jdbc:postgresql://localhost:5432/roaming_db
    username: roaming_user
    password: roaming_pass
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  logging:
    level:
      org.springframework.batch: INFO
      com.roaming: DEBUG